# SETUP

The first part of the code sets up the pca_wavelet network, the training comes later. Most of this code comes from the original authors

In [2]:
import sys
import time
sys.path.append('../segmentation_helper')

import tensorflow as tf
import keras
import tqdm
import matplotlib.pyplot as plt
import numpy as np
import data_loader as dl
import model_broker as mb
import os
import pandas as pd
import seaborn as sns

tf.keras.backend.set_floatx("float64")

GPU device not found
Found GPU at: 


In [3]:
def scaledtanh(x): 
    return tf.math.tanh(x*0.5)

def scaledatanh(x):
    return tf.math.atanh(x)*2.0


In [4]:
def conv_calculate_A_and_b(imghead, seghead, img_train,seg_train):
    n = 0.0
    
    imdecom_shape = imghead(next(iter(img_train))[0]).shape
    img_channels = imdecom_shape[3] # shape_0
    imdecom_2d_shape = imdecom_shape[1]*imdecom_shape[2] #shape_1
    
    segdecom_shape = seghead(next(iter(seg_train))[0]).shape
    seg_channels = segdecom_shape[3] # shape_0
    segdecom_2d_shape = segdecom_shape[1]*segdecom_shape[2] #shape_1
    

    xxt = np.zeros([img_channels,img_channels])
    yxt = np.zeros([img_channels,seg_channels])
    x = np.ones([imdecom_2d_shape])
    x_m = np.zeros([img_channels])
    y = np.ones([segdecom_2d_shape]) 
    y_m = np.zeros([seg_channels])

    bar = tqdm.notebook.tqdm(total = int(img_train.cardinality()))

    for item in iter(zip(img_train,seg_train)):
        bar.update(1)
        image = item[0][0]
        segmentation = item[1][0]

        imgdecom = imghead(image)
        segdecom = seghead(segmentation)

        mat = tf.reshape(imgdecom,[-1,seg_channels])
        segmat = tf.reshape(segdecom,[-1,img_channels])

        cov = tf.tensordot(mat,mat,[0,0])
        xxt += cov
        #del cov

        segcov = tf.tensordot(mat,segmat,[0,0])
        yxt += segcov
        #del segcov

        x_m += tf.linalg.matvec(mat,x,transpose_a=True)
        y_m += tf.linalg.matvec(segmat,y,transpose_a=True)

        n += 1
    xxt = xxt - tf.matmul([x_m],[x_m],transpose_a=True)/n
    yxt = yxt - tf.matmul([x_m],[y_m],transpose_a=True)/n
    inverse_xxt = tf.linalg.pinv(xxt)
    A = tf.matmul(inverse_xxt,yxt)
    b = (y_m - tf.linalg.matvec(A,x_m,transpose_a=True))/n
    A_filter = tf.reshape(A,(1,1,seg_channels,seg_channels))
    return A_filter,b

In [5]:
def connected_calculate_A_and_b(imghead, seghead, img_train,seg_train):
    imgflat = np.prod(imghead(next(iter(img_train))[0]).shape)
    segflat = np.prod(seghead(next(iter(seg_train))[0]).shape)
    end_shape = next(iter(seg_train))[0].shape
    n = 0.0

    xxt = np.zeros([imgflat])
    yxt = np.zeros([segflat])
    x = np.zeros([imgflat])
    y = np.zeros([segflat]) 

    bar = tqdm.notebook.tqdm(total = int(img_train.cardinality()))

    for item in iter(zip(img_train,seg_train)):

        bar.update(1)

        image = item[0][0]
        segmentation = item[1][0]

        imgdecom = imghead(image)
        segdecom = seghead(segmentation)

        mat = tf.reshape(imgdecom,[-1])
        segmat = tf.reshape(segdecom,[-1])

        cov = tf.matmul([mat],[mat],transpose_a=True)
        xxt += cov
        segcov = tf.matmul([mat],[segmat],transpose_a=True)
        yxt += segcov
        x+=mat
        y+=segmat
        n += 1
        
    xxt = xxt - tf.matmul([x],[x],transpose_a=True)/n
    yxt = yxt - tf.matmul([x],[y],transpose_a=True)/n
    inverse_xxt = tf.linalg.pinv(xxt)
    A = tf.linalg.matmul(inverse_xxt,yxt)
    b = (y - tf.linalg.matvec(A,x,transpose_a=True))/n
    return A,b

In [6]:
def build_model_instance(train,
                test,
                dataset,
                model_name,
                keep_percent=1.0,
                count=3,
                sample_size=100,
                activity_regularizer=None,
                inverse_activity_regularizer=None,
                activation_before=False,
                check_build=False):
    
    stats = None
    
    broker = mb.ModelBroker(trainset=train,
                                testset=test,
                                dirname=dataset+"_"+model_name,
                                keep_percent=keep_percent,
                                count=count,
                                sample_size=sample_size,
                                activity_regularizer = activity_regularizer,
                                inverse_activity_regularizer=inverse_activity_regularizer,
                                activation_before=activation_before)
    
    head,invhead = broker.build_model()
    head,invhead = broker.load_model()    
    if check_build:
        train_psnr,train_ncc = broker.check_build(head,invhead,train,stats_only=True)
        test_psnr,test_ncc = broker.check_build(head,invhead,test,stats_only=True)
        stats = (train_psnr,train_ncc,test_psnr,test_ncc)
    return head,invhead, stats

In [7]:
def conv_metric_calculate(img_ds,seg_ds,A_filter,b):
    threshold_intensity = 0.03
    dice_coeff_vals = []
    iou_coeff_vals = []
    n = 0
    
    for image,seg_base in iter(zip(img_ds,seg_ds)):
        imgdecom = imghead(image[0])
        conv = tf.nn.conv2d(imgdecom, A_filter,1,"VALID")
        conv = tf.nn.bias_add(conv,b)
        seg = seginvhead(conv)
        y_true = tf.cast(tf.reduce_min(seg_base[0],2)==0,tf.float64)
        y_pred = tf.cast(tf.reduce_min(seg[0],2)<threshold_intensity,tf.float64)
        dice_coeff_vals.append(dice_coef(y_true,y_pred))
        iou_coeff_vals.append(iou_coef(y_true,y_pred))
        n+=1
    return iou_coeff_vals,dice_coeff_vals,n


In [8]:
def connected_metric_calculate(img_ds,seg_ds,A,b):
    threshold_intensity = 0.01
    dice_coeff_vals = []
    iou_coeff_vals = []
    n = 0
    reconstruct = seghead(next(iter(seg_ds))[0]).shape
    for image,seg_base in iter(zip(img_ds,seg_ds)):
        imgdecom = imghead(image[0])
        imgdecom = tf.reshape(imgdecom,(1,-1))
        segdecom = tf.linalg.matvec(A,imgdecom,transpose_a=True)+b
        seg = seginvhead(tf.reshape(segdecom,(reconstruct)))
        y_true = tf.cast(tf.reduce_min(seg_base[0],2)==0,tf.float64)
        y_pred = tf.cast(tf.reduce_min(seg[0],2)<threshold_intensity,tf.float64)
        dice_coeff_vals.append(dice_coef(y_true,y_pred))
        iou_coeff_vals.append(iou_coef(y_true,y_pred))
        n+=1
    return iou_coeff_vals,dice_coeff_vals,n

In [9]:
def calculate_metrics(seg_ds,img_ds,imghead,seghead,seginvhead,A,b,mode):
    if mode == "conv":
        iou_coeff_vals,dice_coeff_vals,n = conv_metric_calculate(img_ds,seg_ds,A,b)
    else:
        iou_coeff_vals,dice_coeff_vals,n = connected_metric_calculate(img_ds,seg_ds,A,b)
    dice_coeff_mean = sum(dice_coeff_vals)/n
    iou_coeff_mean = sum(iou_coeff_vals)/n
    dice_coeff_std = (sum([((x - dice_coeff_mean) ** 2) for x in dice_coeff_vals]) / n)**0.5
    iou_coeff_std = (sum([((x - iou_coeff_mean) ** 2) for x in iou_coeff_vals]) / n)**0.5
    return dice_coeff_mean, iou_coeff_mean, dice_coeff_std, iou_coeff_std

In [10]:
def dice_coef(y_true, y_pred,smooth=1):
    y_true_f = tf.reshape(y_true,-1)
    y_pred_f =tf.reshape(y_pred,-1)
    intersection = tf.reduce_sum(y_true_f * y_pred_f,0)

    return float((2. * intersection+smooth) / (tf.reduce_sum(y_true_f) + tf.reduce_sum(y_pred_f)+smooth))

In [11]:
def iou_coef(y_true, y_pred,smooth=1):
  intersection = tf.reduce_sum(y_true * y_pred, 0)
  union = tf.reduce_sum(y_true,0)+tf.reduce_sum(y_pred,0)-intersection
  iou = tf.reduce_mean((intersection+1) / (union+1), 0)
  return float(iou)

In [30]:
counts_exp = [("count",i) for i in range(4,6)]
keep_percents_exp = [("keep_percent",i/10) for i in range(4,12,2)]
train_sizes_exp = [("train_size",i*2000) for i in range(1,3)] + [("train_size",None)]
res_exp = [("res",2**i) for i in range(6,9,2)]
counts_exp = [("count",i) for i in range(4,6)]
experiments = [("skip",0)] + keep_percents_exp# + train_sizes_exp + counts_exp +  res_exp 

In [31]:
experiments

[('skip', 0),
 ('keep_percent', 0.4),
 ('keep_percent', 0.6),
 ('keep_percent', 0.8),
 ('keep_percent', 1.0)]

In [ ]:
#change mode between conv and connected to explore differenet linear inverse methods
for mode in ["conv","connected"]:
    test_size = 300

    dataset = "pets"

    nudge = np.random.randint(0,1000000)

    if mode == "conv":
        calculate_A_and_b = conv_calculate_A_and_b
    else:
        calculate_A_and_b = connected_calculate_A_and_b

    df = pd.DataFrame()

    save_name = mode+"_formal_experiment_"+str(nudge)
    print(f"saving results to:{save_name}")
    for settings in tqdm.notebook.tqdm(experiments):

        #These are the standard experiment settings
        activity_regularizer = scaledtanh
        inverse_activity_regularizer = scaledatanh
        count = 3
        keep_percent = 0.1
        train_size = None
        res = 128

        #Initialise the experiment record for this iteration
        record = pd.Series()

        #Change the values of the paramaters passed into the model builder and data loader
        variable, value = settings
        if variable == "count":
            count = value
        if variable == "keep_percent":
            keep_percent = value
        if variable == "train_size":
            train_size = value
        if variable == "res":
            res = value

        #Load the datasets
        loader = dl.DataLoader(IMAGE_SIZE=res,dataset=dataset,take=train_size)
        img_ds = loader.import_processed_img()
        seg_ds = loader.import_processed_seg()
        cardinality = int(img_ds.cardinality())

        #Generate train/test splits
        img_test = img_ds.take(test_size)
        seg_test = seg_ds.take(test_size)
        img_train = img_ds.skip(test_size)
        seg_train = seg_ds.skip(test_size)    

        #Record experiment parameters
        record["resolution"]=res
        record["count"]=count
        record["keep_percent"] = keep_percent
        record["activity_regularizer"] = activity_regularizer != None
        record["training_data_size"] = train_size

        #Training image reconstruction network
        img_train_start = time.time()
        imghead, imginvhead,stats = build_model_instance(img_train,img_test,dataset,"img",keep_percent = keep_percent,count=count,check_build=True)
        psnr_train,ncc_train,psnr_test,ncc_test = stats
        img_train_end = time.time()

        #Record values from image reconstruction network experiements
        record["img_channel_size"] = imghead(next(iter(img_train))[0]).shape[-1]
        record["img_train_time"] = img_train_end - img_train_start
        record["train_img_psnr"] = psnr_train
        record["train_img_ncc"] = ncc_train
        record["test_img_psnr"] = psnr_test
        record["test_img_ncc"] = ncc_test

        #Training segmentation reconstruction network
        seg_train_start = time.time()
        seghead, seginvhead,stats = build_model_instance(seg_train,seg_test,dataset,"seg",count=count,keep_percent = keep_percent,check_build=True)
        psnr_train,ncc_train,psnr_test,ncc_test = stats
        seg_train_end = time.time()

        #Record values from segmentation reconstruction network experiements
        record["seg_channel_size"] = seghead(next(iter(seg_train))[0]).shape[-1]
        record["seg_train_time"] = img_train_end - img_train_start
        record["train_seg_psnr"] = psnr_train
        record["train_seg_ncc"] = ncc_train
        record["test_seg_psnr"] = psnr_test
        record["test_seg_ncc"] = ncc_test

        #Calculate A and b
        train_time_start = time.time()
        A,b = calculate_A_and_b(imghead,seghead,img_train,seg_train)
        train_time_end = time.time()
        record["linear_inverse_train_time"] = train_time_end - train_time_start 

        #Caculate metrics of image segmentation network
        dice_mean_test, iou_mean_test, dice_std_test, iou_std_test = calculate_metrics(seg_test,img_test,imghead,seghead,seginvhead,A,b,mode)
        dice_mean_train, iou_mean_train, dice_std_train, iou_std_train = calculate_metrics(seg_train,img_train,imghead,seghead,seginvhead,A,b,mode)

        #Record metrics
        record["dice_mean_train"] = dice_mean_train
        #record["iou_mean_train"] = iou_mean_train
        record["dice_std_train"] = dice_std_train
        #record["iou_std_train"] = iou_std_train
        record["dice_mean_test"] = dice_mean_test
        #record["iou_mean_test"] = iou_mean_test
        record["dice_std_test"] = dice_std_test
        #record["iou_std_test"] = iou_std_test

        #Append experiment to dataframe, and save most recent dataframe
        df = df.append(record,ignore_index=True)
        df.to_csv(save_name)

saving results to:conv_formal_experiment_54912


  0%|          | 0/5 [00:00<?, ?it/s]

keep_percent 0.20629283704945683


<ipython-input-33-5eb84df89684>:29: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  record = pd.Series()


meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.shape (1, 1, 1, 27, 5)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([45 45], shape=(2,), dtype=int32)
keep_channels 9 keep_max 80.0
keep_channels 9
ufilts.shape (1, 1, 1, 45, 9)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([81 81], shape=(2,), dtype=int32)
keep_channels 16 keep_max 576.0
keep_channels 16
ufilts.shape (1, 1, 1, 81, 16)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 16)
keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.shape (1, 1, 1, 27, 5)
end loop 6

array([[[0.21162684, 0.09790135, 0.0665288 ],
        [0.20883885, 0.10073888, 0.07169118],
        [0.2164242 , 0.09884177, 0.06757908],
        ...,
        [0.2797488 , 0.2130821 , 0.17942373],
        [0.27120912, 0.22129288, 0.17218497],
        [0.26838118, 0.21306559, 0.17790934]],

       [[0.2211974 , 0.10355034, 0.07135058],
        [0.20741877, 0.10505515, 0.07519914],
        [0.22539301, 0.10368916, 0.06551514],
        ...,
        [0.29071429, 0.23581232, 0.19328254],
        [0.28647366, 0.2319853 , 0.18265931],
        [0.27116317, 0.21626121, 0.16928712]],

       [[0.20247564, 0.09950382, 0.06805731],
        [0.20884149, 0.09505472, 0.07702206],
        [0.22576307, 0.10300245, 0.0598652 ],
        ...,
        [0.29635492, 0.23360978, 0.18262939],
        [0.29666054, 0.2251326 , 0.19777355],
        [0.28988373, 0.22536166, 0.17971216]],

       ...,

       [[0.70401281, 0.51205701, 0.28423715],
        [0.69345009, 0.55425429, 0.28250661],
        [0.6865474 , 0

array([[[0.31272358, 0.32361558, 0.29820484],
        [0.31193513, 0.32502395, 0.29021668],
        [0.3099868 , 0.33001161, 0.29664665],
        ...,
        [0.28866425, 0.25707817, 0.21427792],
        [0.28846318, 0.24594535, 0.19817851],
        [0.2431497 , 0.240153  , 0.19564041]],

       [[0.32199422, 0.33907256, 0.29442403],
        [0.31503335, 0.32776743, 0.288838  ],
        [0.32305023, 0.34004864, 0.300248  ],
        ...,
        [0.26030803, 0.19661602, 0.14610907],
        [0.24157429, 0.20276742, 0.15124559],
        [0.23732623, 0.20338351, 0.18857566]],

       [[0.33531091, 0.34315404, 0.29845428],
        [0.33677572, 0.34288642, 0.30244812],
        [0.35008377, 0.35924432, 0.33313182],
        ...,
        [0.24312434, 0.1840155 , 0.13597628],
        [0.26333824, 0.1853219 , 0.14950694],
        [0.23001255, 0.20721652, 0.1820188 ]],

       ...,

       [[0.48685852, 0.49200368, 0.28987777],
        [0.49323493, 0.53634971, 0.29418996],
        [0.57753813, 0

array([[[0.31272358, 0.32361558, 0.29820484],
        [0.31193513, 0.32502395, 0.29021668],
        [0.3099868 , 0.33001161, 0.29664665],
        ...,
        [0.28866425, 0.25707817, 0.21427792],
        [0.28846318, 0.24594535, 0.19817851],
        [0.2431497 , 0.240153  , 0.19564041]],

       [[0.32199422, 0.33907256, 0.29442403],
        [0.31503335, 0.32776743, 0.288838  ],
        [0.32305023, 0.34004864, 0.300248  ],
        ...,
        [0.26030803, 0.19661602, 0.14610907],
        [0.24157429, 0.20276742, 0.15124559],
        [0.23732623, 0.20338351, 0.18857566]],

       [[0.33531091, 0.34315404, 0.29845428],
        [0.33677572, 0.34288642, 0.30244812],
        [0.35008377, 0.35924432, 0.33313182],
        ...,
        [0.24312434, 0.1840155 , 0.13597628],
        [0.26333824, 0.1853219 , 0.14950694],
        [0.23001255, 0.20721652, 0.1820188 ]],

       ...,

       [[0.48685852, 0.49200368, 0.28987777],
        [0.49323493, 0.53634971, 0.29418996],
        [0.57753813, 0

keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.shape (1, 1, 1, 27, 5)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([45 45], shape=(2,), dtype=int32)
keep_channels 9 keep_max 80.0
keep_channels 9
ufilts.shape (1, 1, 1, 45, 9)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([81 81], shape=(2,), dtype=int32)
keep_channels 16 keep_max 576.0
keep_channels 16
ufilts.shape (1, 1, 1, 81, 16)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 16)
keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.

array([[[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.06354167, 0.04376532, 0.08933058],
        [0.04769455, 0.03921569, 0.06853554],
        [0.07892157, 0.07451747, 0.12843138]],

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.06070006, 0.0435815 , 0.08123469],
        [0.06077666, 0.0459712 , 0.08707108],
        [0.05784314, 0.03921569, 0.07756587]],

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.05634192, 0.03921569, 0.07842372],
        [0.06395527, 0.04419424, 0.08748468],
        [0.05401348, 0.03921569, 0.07834712]],

       ...,

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.04139859, 0

array([[[0.00741039, 0.00741039, 0.00741039],
        [0.02634804, 0.02634804, 0.02634804],
        [0.03277037, 0.04545037, 0.04174517],
        ...,
        [0.06216491, 0.05903608, 0.06060049],
        [0.06405868, 0.05796569, 0.06060049],
        [0.07039867, 0.05985945, 0.06249426]],

       [[0.01102941, 0.01102941, 0.01102941],
        [0.03921569, 0.03921569, 0.03921569],
        [0.04877451, 0.06768344, 0.06213235],
        ...,
        [0.09403148, 0.08937462, 0.0918256 ],
        [0.09588504, 0.08680683, 0.09086052],
        [0.10580385, 0.0900563 , 0.09416169]],

       [[0.01102941, 0.01102941, 0.01102941],
        [0.03921569, 0.03921569, 0.03921569],
        [0.04877451, 0.0699755 , 0.06213235],
        ...,
        [0.08768383, 0.08245443, 0.09601716],
        [0.08952206, 0.07984069, 0.09503677],
        [0.09944853, 0.07984069, 0.09834559]],

       ...,

       [[0.45220971, 0.43983227, 0.46657667],
        [0.45186314, 0.43850529, 0.46556371],
        [0.44268727, 0

array([[[0.00741039, 0.00741039, 0.00741039],
        [0.02634804, 0.02634804, 0.02634804],
        [0.03277037, 0.04545037, 0.04174517],
        ...,
        [0.06216491, 0.05903608, 0.06060049],
        [0.06405868, 0.05796569, 0.06060049],
        [0.07039867, 0.05985945, 0.06249426]],

       [[0.01102941, 0.01102941, 0.01102941],
        [0.03921569, 0.03921569, 0.03921569],
        [0.04877451, 0.06768344, 0.06213235],
        ...,
        [0.09403148, 0.08937462, 0.0918256 ],
        [0.09588504, 0.08680683, 0.09086052],
        [0.10580385, 0.0900563 , 0.09416169]],

       [[0.01102941, 0.01102941, 0.01102941],
        [0.03921569, 0.03921569, 0.03921569],
        [0.04877451, 0.0699755 , 0.06213235],
        ...,
        [0.08768383, 0.08245443, 0.09601716],
        [0.08952206, 0.07984069, 0.09503677],
        [0.09944853, 0.07984069, 0.09834559]],

       ...,

       [[0.45220971, 0.43983227, 0.46657667],
        [0.45186314, 0.43850529, 0.46556371],
        [0.44268727, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
ufilts.shape (1, 1, 1, 27, 8)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([72 72], shape=(2,), dtype=int32)
keep_channels 23 keep_max 128.0
keep_channels 23
ufilts.shape (1, 1, 1, 72, 23)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([207 207], shape=(2,), dtype=int32)
keep_channels 67 keep_max 1472.0
keep_channels 67
ufilts.shape (1, 1, 1, 207, 67)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 67)
keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
u

array([[[0.10351755, 0.12069211, 0.12824301],
        [0.1912064 , 0.22650051, 0.22230321],
        [0.07541624, 0.09102927, 0.09266501],
        ...,
        [0.0632353 , 0.07107843, 0.05931373],
        [0.04942244, 0.06894197, 0.05352065],
        [0.05335478, 0.06876532, 0.06484375]],

       [[0.06597541, 0.08440731, 0.07469172],
        [0.18227467, 0.20087604, 0.21237577],
        [0.16716476, 0.20296703, 0.19965294],
        ...,
        [0.06655728, 0.08224355, 0.07832199],
        [0.08110303, 0.09930157, 0.08784323],
        [0.07754648, 0.09405997, 0.08972479]],

       [[0.05746544, 0.07699932, 0.07037306],
        [0.11217783, 0.11842257, 0.13734107],
        [0.23264903, 0.26607573, 0.2702876 ],
        ...,
        [0.06407711, 0.08110926, 0.06628155],
        [0.06240641, 0.07099275, 0.0631216 ],
        [0.0598944 , 0.07420199, 0.07028043]],

       ...,

       [[0.0588422 , 0.07806373, 0.07237454],
        [0.06459124, 0.08260068, 0.0788962 ],
        [0.06974356, 0

array([[[4.44638491e-01, 3.20132524e-01, 2.17775360e-01],
        [3.72198611e-01, 2.30430454e-01, 1.07973345e-01],
        [2.94085115e-01, 1.44064039e-01, 3.66325863e-02],
        ...,
        [3.13844234e-01, 1.83448225e-01, 1.47081792e-01],
        [2.89456964e-01, 9.77902859e-02, 8.21040124e-02],
        [2.29365811e-01, 6.26991466e-02, 4.06403206e-02]],

       [[3.84880543e-01, 2.60364980e-01, 1.49574906e-01],
        [3.32860380e-01, 1.73648134e-01, 5.98441362e-02],
        [2.37739354e-01, 9.96955410e-02, 2.36098329e-03],
        ...,
        [2.15847120e-01, 7.72173703e-02, 5.38851880e-02],
        [2.92570472e-01, 9.95232090e-02, 8.83731693e-02],
        [2.21664369e-01, 4.64728884e-02, 2.94347443e-02]],

       [[2.89269298e-01, 1.64776742e-01, 4.02611829e-02],
        [3.51338476e-01, 1.76763564e-01, 5.66482842e-02],
        [2.28710935e-01, 9.47074145e-02, 8.39269254e-03],
        ...,
        [2.05422804e-01, 6.66973069e-02, 5.15012257e-02],
        [2.88666129e-01, 1.17

array([[[4.44638491e-01, 3.20132524e-01, 2.17775360e-01],
        [3.72198611e-01, 2.30430454e-01, 1.07973345e-01],
        [2.94085115e-01, 1.44064039e-01, 3.66325863e-02],
        ...,
        [3.13844234e-01, 1.83448225e-01, 1.47081792e-01],
        [2.89456964e-01, 9.77902859e-02, 8.21040124e-02],
        [2.29365811e-01, 6.26991466e-02, 4.06403206e-02]],

       [[3.84880543e-01, 2.60364980e-01, 1.49574906e-01],
        [3.32860380e-01, 1.73648134e-01, 5.98441362e-02],
        [2.37739354e-01, 9.96955410e-02, 2.36098329e-03],
        ...,
        [2.15847120e-01, 7.72173703e-02, 5.38851880e-02],
        [2.92570472e-01, 9.95232090e-02, 8.83731693e-02],
        [2.21664369e-01, 4.64728884e-02, 2.94347443e-02]],

       [[2.89269298e-01, 1.64776742e-01, 4.02611829e-02],
        [3.51338476e-01, 1.76763564e-01, 5.66482842e-02],
        [2.28710935e-01, 9.47074145e-02, 8.39269254e-03],
        ...,
        [2.05422804e-01, 6.66973069e-02, 5.15012257e-02],
        [2.88666129e-01, 1.17

keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
ufilts.shape (1, 1, 1, 27, 8)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([72 72], shape=(2,), dtype=int32)
keep_channels 23 keep_max 128.0
keep_channels 23
ufilts.shape (1, 1, 1, 72, 23)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([207 207], shape=(2,), dtype=int32)
keep_channels 67 keep_max 1472.0
keep_channels 67
ufilts.shape (1, 1, 1, 207, 67)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 67)
keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
u

array([[[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569]],

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569]],

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        ...,
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569]],

       ...,

       [[0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0.03921569, 0.03921569],
        [0.03921569, 0

array([[[0.4519304 , 0.37812859, 0.35032362],
        [0.4800604 , 0.40377367, 0.37632269],
        [0.46909133, 0.39461216, 0.37106743],
        ...,
        [0.38430536, 0.32333028, 0.33080578],
        [0.38707107, 0.32432598, 0.33180147],
        [0.37521449, 0.31246939, 0.31639096]],

       [[0.46597758, 0.37409142, 0.35338065],
        [0.47907594, 0.39350635, 0.37199852],
        [0.45652264, 0.38342214, 0.36773586],
        ...,
        [0.40312502, 0.33756128, 0.33756128],
        [0.39443958, 0.3213391 , 0.32636362],
        [0.40269107, 0.33009106, 0.33411458]],

       [[0.44162765, 0.3681595 , 0.35455656],
        [0.45390624, 0.38331801, 0.37755823],
        [0.48154107, 0.41095284, 0.40516239],
        ...,
        [0.39716607, 0.31873471, 0.31481314],
        [0.37225798, 0.31030944, 0.29958642],
        [0.42965832, 0.34898898, 0.34162912]],

       ...,

       [[0.40401614, 0.3960588 , 0.45258021],
        [0.35948509, 0.37452728, 0.39423564],
        [0.50740516, 0

array([[[0.4519304 , 0.37812859, 0.35032362],
        [0.4800604 , 0.40377367, 0.37632269],
        [0.46909133, 0.39461216, 0.37106743],
        ...,
        [0.38430536, 0.32333028, 0.33080578],
        [0.38707107, 0.32432598, 0.33180147],
        [0.37521449, 0.31246939, 0.31639096]],

       [[0.46597758, 0.37409142, 0.35338065],
        [0.47907594, 0.39350635, 0.37199852],
        [0.45652264, 0.38342214, 0.36773586],
        ...,
        [0.40312502, 0.33756128, 0.33756128],
        [0.39443958, 0.3213391 , 0.32636362],
        [0.40269107, 0.33009106, 0.33411458]],

       [[0.44162765, 0.3681595 , 0.35455656],
        [0.45390624, 0.38331801, 0.37755823],
        [0.48154107, 0.41095284, 0.40516239],
        ...,
        [0.39716607, 0.31873471, 0.31481314],
        [0.37225798, 0.31030944, 0.29958642],
        [0.42965832, 0.34898898, 0.34162912]],

       ...,

       [[0.40401614, 0.3960588 , 0.45258021],
        [0.35948509, 0.37452728, 0.39423564],
        [0.50740516, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channels 10
ufilts.shape (1, 1, 1, 27, 10)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([90 90], shape=(2,), dtype=int32)
keep_channels 33 keep_max 160.0
keep_channels 33
ufilts.shape (1, 1, 1, 90, 33)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([297 297], shape=(2,), dtype=int32)
keep_channels 111 keep_max 2112.0
keep_channels 111
ufilts.shape (1, 1, 1, 297, 111)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 111)
keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channe

array([[[0.35200363, 0.40690559, 0.40690559],
        [0.40586033, 0.46860543, 0.46860543],
        [0.42354283, 0.48236635, 0.49413106],
        ...,
        [0.591115  , 0.6130206 , 0.6059894 ],
        [0.58551461, 0.60904402, 0.6065011 ],
        [0.58364594, 0.61374706, 0.61155647]],

       [[0.36206773, 0.41696969, 0.41696969],
        [0.4003011 , 0.46304619, 0.46304619],
        [0.42048389, 0.47930741, 0.49107212],
        ...,
        [0.58674943, 0.60865504, 0.60162377],
        [0.58113754, 0.60466695, 0.60212404],
        [0.57334298, 0.6034441 , 0.60125351]],

       [[0.36976248, 0.42466444, 0.42466444],
        [0.3715241 , 0.43426919, 0.43426919],
        [0.41899869, 0.47782221, 0.48958692],
        ...,
        [0.59460664, 0.6165123 , 0.60948104],
        [0.58374697, 0.60727638, 0.60473353],
        [0.5686574 , 0.59875846, 0.59656793]],

       ...,

       [[0.19271241, 0.19663398, 0.17414623],
        [0.28180078, 0.28572235, 0.26323462],
        [0.26352873, 0

array([[[0.10400343, 0.10400343, 0.09616029],
        [0.10634335, 0.11026492, 0.09065708],
        [0.09811629, 0.10379279, 0.09050724],
        ...,
        [0.11955758, 0.12984931, 0.06445217],
        [0.12064904, 0.12619534, 0.09114009],
        [0.13251618, 0.12653139, 0.09728573]],

       [[0.11010934, 0.11403091, 0.09442306],
        [0.10140213, 0.10244237, 0.09147853],
        [0.10117619, 0.10455108, 0.0950205 ],
        ...,
        [0.10808824, 0.11654173, 0.06616499],
        [0.11495529, 0.11842017, 0.08260714],
        [0.11822964, 0.12251838, 0.07530685]],

       [[0.10783452, 0.11175609, 0.09214824],
        [0.10160271, 0.10160271, 0.09375957],
        [0.07742514, 0.08526827, 0.06769493],
        ...,
        [0.10332127, 0.10936926, 0.07681909],
        [0.10615809, 0.11400123, 0.07133503],
        [0.1179228 , 0.13341662, 0.05994275]],

       ...,

       [[0.23534438, 0.17987372, 0.11077091],
        [0.26678443, 0.19981618, 0.12941895],
        [0.23936361, 0

array([[[0.10400343, 0.10400343, 0.09616029],
        [0.10634335, 0.11026492, 0.09065708],
        [0.09811629, 0.10379279, 0.09050724],
        ...,
        [0.11955758, 0.12984931, 0.06445217],
        [0.12064904, 0.12619534, 0.09114009],
        [0.13251618, 0.12653139, 0.09728573]],

       [[0.11010934, 0.11403091, 0.09442306],
        [0.10140213, 0.10244237, 0.09147853],
        [0.10117619, 0.10455108, 0.0950205 ],
        ...,
        [0.10808824, 0.11654173, 0.06616499],
        [0.11495529, 0.11842017, 0.08260714],
        [0.11822964, 0.12251838, 0.07530685]],

       [[0.10783452, 0.11175609, 0.09214824],
        [0.10160271, 0.10160271, 0.09375957],
        [0.07742514, 0.08526827, 0.06769493],
        ...,
        [0.10332127, 0.10936926, 0.07681909],
        [0.10615809, 0.11400123, 0.07133503],
        [0.1179228 , 0.13341662, 0.05994275]],

       ...,

       [[0.23534438, 0.17987372, 0.11077091],
        [0.26678443, 0.19981618, 0.12941895],
        [0.23936361, 0

keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channels 10
ufilts.shape (1, 1, 1, 27, 10)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([90 90], shape=(2,), dtype=int32)
keep_channels 33 keep_max 160.0
keep_channels 33
ufilts.shape (1, 1, 1, 90, 33)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([297 297], shape=(2,), dtype=int32)
keep_channels 111 keep_max 2112.0
keep_channels 111
ufilts.shape (1, 1, 1, 297, 111)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 111)
keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channe

array([[[0.21964136, 0.23428597, 0.20217812],
        [0.66190833, 0.62269264, 0.62277502],
        [0.37786937, 0.34962183, 0.34015206],
        ...,
        [0.22739545, 0.26698455, 0.26088485],
        [0.26250002, 0.28380343, 0.26572746],
        [0.24929917, 0.24715456, 0.25903514]],

       [[0.22979857, 0.24052256, 0.21149856],
        [0.63321751, 0.58867091, 0.60263962],
        [0.2914857 , 0.27126035, 0.26772845],
        ...,
        [0.24300992, 0.2596153 , 0.27475014],
        [0.20588331, 0.20674115, 0.22745098],
        [0.25457358, 0.26417357, 0.26723635]],

       [[0.23963408, 0.25856793, 0.22012103],
        [0.6402353 , 0.59709805, 0.61780888],
        [0.19941598, 0.18212028, 0.1800044 ],
        ...,
        [0.17250402, 0.18493029, 0.19886833],
        [0.20361042, 0.21157131, 0.22321826],
        [0.25642234, 0.27995175, 0.27144036]],

       ...,

       [[0.13055205, 0.23727024, 0.11278819],
        [0.15522557, 0.24029182, 0.15555397],
        [0.08923292, 0

array([[[0.10296942, 0.26032045, 0.20422556],
        [0.10089902, 0.24983104, 0.20819643],
        [0.11953221, 0.27078837, 0.20032744],
        ...,
        [0.11754078, 0.24573185, 0.20636059],
        [0.09424882, 0.23934685, 0.20938362],
        [0.05358408, 0.19577157, 0.15162329]],

       [[0.15691829, 0.30082434, 0.22211578],
        [0.19098356, 0.32028189, 0.26577818],
        [0.09201086, 0.24430147, 0.16379395],
        ...,
        [0.1505644 , 0.28096375, 0.23833105],
        [0.17676452, 0.30537972, 0.27242696],
        [0.14130476, 0.2844741 , 0.23738033]],

       [[0.08031174, 0.21760446, 0.1811107 ],
        [0.10688955, 0.26711139, 0.2156499 ],
        [0.08470818, 0.19409803, 0.12975979],
        ...,
        [0.10546971, 0.24719766, 0.21751015],
        [0.11701038, 0.2733686 , 0.22879854],
        [0.10742571, 0.23239268, 0.20417577]],

       ...,

       [[0.14933987, 0.28378093, 0.24573664],
        [0.18119256, 0.30585554, 0.27309716],
        [0.19555759, 0

array([[[0.10296942, 0.26032045, 0.20422556],
        [0.10089902, 0.24983104, 0.20819643],
        [0.11953221, 0.27078837, 0.20032744],
        ...,
        [0.11754078, 0.24573185, 0.20636059],
        [0.09424882, 0.23934685, 0.20938362],
        [0.05358408, 0.19577157, 0.15162329]],

       [[0.15691829, 0.30082434, 0.22211578],
        [0.19098356, 0.32028189, 0.26577818],
        [0.09201086, 0.24430147, 0.16379395],
        ...,
        [0.1505644 , 0.28096375, 0.23833105],
        [0.17676452, 0.30537972, 0.27242696],
        [0.14130476, 0.2844741 , 0.23738033]],

       [[0.08031174, 0.21760446, 0.1811107 ],
        [0.10688955, 0.26711139, 0.2156499 ],
        [0.08470818, 0.19409803, 0.12975979],
        ...,
        [0.10546971, 0.24719766, 0.21751015],
        [0.11701038, 0.2733686 , 0.22879854],
        [0.10742571, 0.23239268, 0.20417577]],

       ...,

       [[0.14933987, 0.28378093, 0.24573664],
        [0.18119256, 0.30585554, 0.27309716],
        [0.19555759, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.41258567409891367
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 11 keep_max 12.0
keep_channels 11
ufilts.shape (1, 1, 1, 27, 11)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([99 99], shape=(2,), dtype=int32)
keep_channels 40 keep_max 176.0
keep_channels 40
ufilts.shape (1, 1, 1, 99, 40)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([360 360], shape=(2,), dtype=int32)
keep_channels 148 keep_max 2560.0
keep_channels 148
ufilts.shape (1, 1, 1, 360, 148)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 148)
keep_percent 0.41258567409891367
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 11 keep_max 12.0
keep_ch

array([[[4.64564204e-01, 3.54760289e-01, 2.04821542e-01],
        [3.99210125e-01, 2.89406210e-01, 1.39467493e-01],
        [3.57168168e-01, 2.47364253e-01, 9.74255130e-02],
        ...,
        [1.02574490e-01, 1.08911619e-01, 3.91103700e-02],
        [8.96468103e-01, 7.89301872e-01, 4.03806686e-01],
        [5.38513958e-01, 3.69163603e-01, 2.02443317e-01]],

       [[4.47600722e-01, 3.41718376e-01, 1.66412011e-01],
        [4.48845387e-01, 3.42963040e-01, 1.67656630e-01],
        [3.78857434e-01, 2.72975087e-01, 9.76686925e-02],
        ...,
        [2.82987714e-01, 2.71930546e-01, 1.18594900e-01],
        [9.97599721e-01, 9.01644826e-01, 5.13439238e-01],
        [5.03032207e-01, 3.82413268e-01, 1.65063009e-01]],

       [[4.50121582e-01, 3.52082372e-01, 1.39306650e-01],
        [4.55336630e-01, 3.57297421e-01, 1.44521683e-01],
        [4.48561966e-01, 3.50522757e-01, 1.37747020e-01],
        ...,
        [5.27546763e-01, 4.68176514e-01, 2.49537572e-01],
        [8.74929130e-01, 7.33

array([[[0.01568628, 0.02204351, 0.01770833],
        [0.0132274 , 0.01958463, 0.01524945],
        [0.00399816, 0.01035539, 0.00689554],
        ...,
        [0.03906465, 0.04690779, 0.04298622],
        [0.02526042, 0.03310356, 0.02918199],
        [0.08586355, 0.10154982, 0.10547139]],

       [[0.01903315, 0.01903315, 0.02473168],
        [0.0200911 , 0.0200911 , 0.02578963],
        [0.01318048, 0.01318048, 0.01887901],
        ...,
        [0.04116115, 0.04900429, 0.04508272],
        [0.03208415, 0.03992729, 0.03600572],
        [0.09195773, 0.107644  , 0.11156557]],

       [[0.01300551, 0.02352941, 0.00165441],
        [0.01645867, 0.02698256, 0.00165441],
        [0.0115962 , 0.0221201 , 0.00150577],
        ...,
        [0.04454657, 0.05238971, 0.04846814],
        [0.03892463, 0.04676777, 0.0428462 ],
        [0.09885111, 0.11453738, 0.11845895]],

       ...,

       [[0.23433121, 0.2347448 , 0.24258794],
        [0.23488052, 0.23488052, 0.24272366],
        [0.23488052, 0

array([[[0.01568628, 0.02204351, 0.01770833],
        [0.0132274 , 0.01958463, 0.01524945],
        [0.00399816, 0.01035539, 0.00689554],
        ...,
        [0.03906465, 0.04690779, 0.04298622],
        [0.02526042, 0.03310356, 0.02918199],
        [0.08586355, 0.10154982, 0.10547139]],

       [[0.01903315, 0.01903315, 0.02473168],
        [0.0200911 , 0.0200911 , 0.02578963],
        [0.01318048, 0.01318048, 0.01887901],
        ...,
        [0.04116115, 0.04900429, 0.04508272],
        [0.03208415, 0.03992729, 0.03600572],
        [0.09195773, 0.107644  , 0.11156557]],

       [[0.01300551, 0.02352941, 0.00165441],
        [0.01645867, 0.02698256, 0.00165441],
        [0.0115962 , 0.0221201 , 0.00150577],
        ...,
        [0.04454657, 0.05238971, 0.04846814],
        [0.03892463, 0.04676777, 0.0428462 ],
        [0.09885111, 0.11453738, 0.11845895]],

       ...,

       [[0.23433121, 0.2347448 , 0.24258794],
        [0.23488052, 0.23488052, 0.24272366],
        [0.23488052, 0

keep_percent 0.41258567409891367
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 11 keep_max 12.0
keep_channels 11
ufilts.shape (1, 1, 1, 27, 11)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([99 99], shape=(2,), dtype=int32)
keep_channels 40 keep_max 176.0
keep_channels 40
ufilts.shape (1, 1, 1, 99, 40)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([360 360], shape=(2,), dtype=int32)
keep_channels 148 keep_max 2560.0
keep_channels 148
ufilts.shape (1, 1, 1, 360, 148)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 148)
keep_percent 0.41258567409891367
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 11 keep_max 12.0
keep_ch

array([[[0.10588235, 0.12941177, 0.08235294],
        [0.10588235, 0.12941177, 0.08235294],
        [0.10588235, 0.12941177, 0.08235294],
        ...,
        [0.78431374, 0.93333334, 0.98431373],
        [0.78431374, 0.93333334, 0.98431373],
        [0.78431374, 0.93333334, 0.98431373]],

       [[0.10261948, 0.12614891, 0.07909007],
        [0.10261948, 0.12614891, 0.07909007],
        [0.10261948, 0.12614891, 0.07909007],
        ...,
        [0.78431374, 0.93333334, 0.98431373],
        [0.78431374, 0.93333334, 0.98431373],
        [0.78431374, 0.93333334, 0.98431373]],

       [[0.10196079, 0.1254902 , 0.07843138],
        [0.10196079, 0.1254902 , 0.07843138],
        [0.10196079, 0.1254902 , 0.07843138],
        ...,
        [0.78823531, 0.93725491, 0.98823529],
        [0.78437501, 0.93339461, 0.984375  ],
        [0.78431374, 0.93333334, 0.98431373]],

       ...,

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0

array([[[0.38370097, 0.34448528, 0.3797794 ],
        [0.37916666, 0.34289217, 0.3762255 ],
        [0.38504902, 0.35759804, 0.38504902],
        ...,
        [0.14620098, 0.13835785, 0.15796569],
        [0.52230394, 0.51642162, 0.5409314 ],
        [0.46948528, 0.46360296, 0.4979167 ]],

       [[0.39129901, 0.35208333, 0.38737744],
        [0.38149512, 0.3452206 , 0.37855393],
        [0.3822304 , 0.35477942, 0.3822304 ],
        ...,
        [0.17941177, 0.17156863, 0.19117647],
        [0.49607843, 0.49019611, 0.5147059 ],
        [0.47781864, 0.47193626, 0.50625002]],

       [[0.39117646, 0.35196078, 0.38725489],
        [0.39607844, 0.35686275, 0.39215687],
        [0.40000001, 0.36078432, 0.39607844],
        ...,
        [0.38272062, 0.37487748, 0.39448532],
        [0.4879902 , 0.48210785, 0.50661767],
        [0.48419118, 0.47830883, 0.51262259]],

       ...,

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0

array([[[0.38370097, 0.34448528, 0.3797794 ],
        [0.37916666, 0.34289217, 0.3762255 ],
        [0.38504902, 0.35759804, 0.38504902],
        ...,
        [0.14620098, 0.13835785, 0.15796569],
        [0.52230394, 0.51642162, 0.5409314 ],
        [0.46948528, 0.46360296, 0.4979167 ]],

       [[0.39129901, 0.35208333, 0.38737744],
        [0.38149512, 0.3452206 , 0.37855393],
        [0.3822304 , 0.35477942, 0.3822304 ],
        ...,
        [0.17941177, 0.17156863, 0.19117647],
        [0.49607843, 0.49019611, 0.5147059 ],
        [0.47781864, 0.47193626, 0.50625002]],

       [[0.39117646, 0.35196078, 0.38725489],
        [0.39607844, 0.35686275, 0.39215687],
        [0.40000001, 0.36078432, 0.39607844],
        ...,
        [0.38272062, 0.37487748, 0.39448532],
        [0.4879902 , 0.48210785, 0.50661767],
        [0.48419118, 0.47830883, 0.51262259]],

       ...,

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.4444444444444444
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 12 keep_max 12.0
keep_channels 12
ufilts.shape (1, 1, 1, 27, 12)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([108 108], shape=(2,), dtype=int32)
keep_channels 48 keep_max 192.0
keep_channels 48
ufilts.shape (1, 1, 1, 108, 48)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([432 432], shape=(2,), dtype=int32)
keep_channels 192 keep_max 3072.0
keep_channels 192
ufilts.shape (1, 1, 1, 432, 192)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 192)
keep_percent 0.4444444444444444
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 12 keep_max 12.0
keep_c

array([[[0.47668508, 0.5462929 , 0.6217984 ],
        [0.43164062, 0.46524972, 0.49892771],
        [0.32035846, 0.34916514, 0.41117495],
        ...,
        [0.50984222, 0.6177007 , 0.783364  ],
        [0.31337318, 0.42611825, 0.5011183 ],
        [0.22912839, 0.34776348, 0.37946537]],

       [[0.67967218, 0.64309132, 0.70900738],
        [0.59950984, 0.59339005, 0.63496482],
        [0.58852637, 0.63525581, 0.63003218],
        ...,
        [0.54111522, 0.6589691 , 0.796875  ],
        [0.28272825, 0.41132045, 0.4775812 ],
        [0.16270681, 0.29713544, 0.34542742]],

       [[0.24915749, 0.21979932, 0.2278033 ],
        [0.53768384, 0.5172258 , 0.52214313],
        [0.63233763, 0.63568479, 0.59184283],
        ...,
        [0.48643535, 0.62013638, 0.73147213],
        [0.25842527, 0.40248162, 0.48923868],
        [0.36727178, 0.51738662, 0.61328894]],

       ...,

       [[0.56760114, 0.54374236, 0.59724265],
        [0.45431221, 0.46488971, 0.51519608],
        [0.42602634, 0

array([[[0.60549939, 0.66457164, 0.64172816],
        [0.64604759, 0.712331  , 0.69036412],
        [0.59109557, 0.66830027, 0.66096669],
        ...,
        [0.55567437, 0.59997034, 0.58947015],
        [0.6175279 , 0.66462761, 0.6409297 ],
        [0.55254292, 0.59598154, 0.57982206]],

       [[0.60281843, 0.65740299, 0.64122152],
        [0.59334934, 0.63653541, 0.6095897 ],
        [0.58102983, 0.65248263, 0.63535082],
        ...,
        [0.61299884, 0.66970962, 0.66328555],
        [0.63109589, 0.66380072, 0.63919896],
        [0.62967676, 0.67986584, 0.66403139]],

       [[0.63334441, 0.6783306 , 0.65827852],
        [0.62239134, 0.65625477, 0.64197904],
        [0.400343  , 0.44861609, 0.42678294],
        ...,
        [0.58999079, 0.62602735, 0.59570462],
        [0.60244119, 0.66949201, 0.65915191],
        [0.58913219, 0.63048553, 0.60342306]],

       ...,

       [[0.11906332, 0.26807168, 0.0767018 ],
        [0.1206926 , 0.29025331, 0.13390706],
        [0.11865402, 0

array([[[0.60549939, 0.66457164, 0.64172816],
        [0.64604759, 0.712331  , 0.69036412],
        [0.59109557, 0.66830027, 0.66096669],
        ...,
        [0.55567437, 0.59997034, 0.58947015],
        [0.6175279 , 0.66462761, 0.6409297 ],
        [0.55254292, 0.59598154, 0.57982206]],

       [[0.60281843, 0.65740299, 0.64122152],
        [0.59334934, 0.63653541, 0.6095897 ],
        [0.58102983, 0.65248263, 0.63535082],
        ...,
        [0.61299884, 0.66970962, 0.66328555],
        [0.63109589, 0.66380072, 0.63919896],
        [0.62967676, 0.67986584, 0.66403139]],

       [[0.63334441, 0.6783306 , 0.65827852],
        [0.62239134, 0.65625477, 0.64197904],
        [0.400343  , 0.44861609, 0.42678294],
        ...,
        [0.58999079, 0.62602735, 0.59570462],
        [0.60244119, 0.66949201, 0.65915191],
        [0.58913219, 0.63048553, 0.60342306]],

       ...,

       [[0.11906332, 0.26807168, 0.0767018 ],
        [0.1206926 , 0.29025331, 0.13390706],
        [0.11865402, 0

keep_percent 0.4444444444444444
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 12 keep_max 12.0
keep_channels 12
ufilts.shape (1, 1, 1, 27, 12)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([108 108], shape=(2,), dtype=int32)
keep_channels 48 keep_max 192.0
keep_channels 48
ufilts.shape (1, 1, 1, 108, 48)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([432 432], shape=(2,), dtype=int32)
keep_channels 192 keep_max 3072.0
keep_channels 192
ufilts.shape (1, 1, 1, 432, 192)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 192)
keep_percent 0.4444444444444444
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 12 keep_max 12.0
keep_c

array([[[0.53581834, 0.54366148, 0.39072028],
        [0.53666753, 0.54451066, 0.39941263],
        [0.54254967, 0.54647124, 0.41313788],
        ...,
        [0.97247243, 0.97250307, 0.97248775],
        [0.96292895, 0.96292895, 0.95508581],
        [0.96113831, 0.96542752, 0.95543981]],

       [[0.56221926, 0.5700624 , 0.4171212 ],
        [0.57579732, 0.58364046, 0.43572375],
        [0.58318019, 0.59102333, 0.44310662],
        ...,
        [0.95932907, 0.96325064, 0.97893691],
        [0.95796567, 0.96078432, 0.95937502],
        [0.95746523, 0.96128482, 0.95435047]],

       [[0.58745408, 0.59529722, 0.44443935],
        [0.59396875, 0.60389525, 0.45303738],
        [0.60389912, 0.62246525, 0.4687275 ],
        ...,
        [0.93618262, 0.94010419, 0.94794732],
        [0.94013482, 0.94117647, 0.94325984],
        [0.93333334, 0.93956107, 0.94048566]],

       ...,

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0

array([[[0.97647059, 0.94175857, 0.90617341],
        [0.98329741, 0.95584643, 0.92447388],
        [0.98553038, 0.95676059, 0.92472857],
        ...,
        [0.99462318, 0.958318  , 0.91764706],
        [0.98910844, 0.95468748, 0.91764706],
        [0.99215686, 0.95294118, 0.9137255 ]],

       [[0.98271054, 0.94799852, 0.91241336],
        [0.97764176, 0.95019078, 0.91881824],
        [0.70341468, 0.67782819, 0.6493662 ],
        ...,
        [0.99228156, 0.95597643, 0.91037285],
        [0.99215686, 0.96078432, 0.91764706],
        [0.99356616, 0.95435047, 0.91513479]],

       [[0.98017842, 0.95272744, 0.92135489],
        [0.98512346, 0.94982934, 0.92237836],
        [0.98576897, 0.9554075 , 0.9254902 ],
        ...,
        [0.98862183, 0.9582603 , 0.92049992],
        [0.99192494, 0.95663083, 0.92133671],
        [0.99607843, 0.95686275, 0.91764706]],

       ...,

       [[0.28583914, 0.43878821, 0.15647763],
        [0.50777709, 0.54873532, 0.19163364],
        [0.43106356, 0

array([[[0.97647059, 0.94175857, 0.90617341],
        [0.98329741, 0.95584643, 0.92447388],
        [0.98553038, 0.95676059, 0.92472857],
        ...,
        [0.99462318, 0.958318  , 0.91764706],
        [0.98910844, 0.95468748, 0.91764706],
        [0.99215686, 0.95294118, 0.9137255 ]],

       [[0.98271054, 0.94799852, 0.91241336],
        [0.97764176, 0.95019078, 0.91881824],
        [0.70341468, 0.67782819, 0.6493662 ],
        ...,
        [0.99228156, 0.95597643, 0.91037285],
        [0.99215686, 0.96078432, 0.91764706],
        [0.99356616, 0.95435047, 0.91513479]],

       [[0.98017842, 0.95272744, 0.92135489],
        [0.98512346, 0.94982934, 0.92237836],
        [0.98576897, 0.9554075 , 0.9254902 ],
        ...,
        [0.98862183, 0.9582603 , 0.92049992],
        [0.99192494, 0.95663083, 0.92133671],
        [0.99607843, 0.95686275, 0.91764706]],

       ...,

       [[0.28583914, 0.43878821, 0.15647763],
        [0.50777709, 0.54873532, 0.19163364],
        [0.43106356, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

saving results to:connected_formal_experiment_632530


  0%|          | 0/5 [00:00<?, ?it/s]

keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.shape (1, 1, 1, 27, 5)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([45 45], shape=(2,), dtype=int32)
keep_channels 9 keep_max 80.0
keep_channels 9
ufilts.shape (1, 1, 1, 45, 9)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([81 81], shape=(2,), dtype=int32)
keep_channels 16 keep_max 576.0
keep_channels 16
ufilts.shape (1, 1, 1, 81, 16)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 16)
keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.

array([[[0.29135337, 0.42748401, 0.1476541 ],
        [0.37114593, 0.49090865, 0.21254046],
        [0.3234995 , 0.35659301, 0.2577146 ],
        ...,
        [0.39048257, 0.41810063, 0.35832807],
        [0.26914349, 0.24720675, 0.20898749],
        [0.26816791, 0.25510231, 0.2023873 ]],

       [[0.31207633, 0.47442579, 0.17829686],
        [0.37814584, 0.4978475 , 0.20781586],
        [0.35098207, 0.32423791, 0.28669029],
        ...,
        [0.35962799, 0.37560844, 0.33212578],
        [0.29698032, 0.29232034, 0.25578758],
        [0.24664523, 0.23962928, 0.18324861]],

       [[0.35158381, 0.47236663, 0.24291229],
        [0.38062817, 0.43298244, 0.22417472],
        [0.30592662, 0.33092016, 0.29795879],
        ...,
        [0.3514902 , 0.36582199, 0.34168631],
        [0.32540715, 0.33575538, 0.28981841],
        [0.23631448, 0.24786472, 0.18863359]],

       ...,

       [[0.46877515, 0.55178684, 0.32733035],
        [0.48545617, 0.59976685, 0.43128568],
        [0.4176667 , 0

array([[[0.60549939, 0.66457164, 0.64172816],
        [0.64604759, 0.712331  , 0.69036412],
        [0.59109557, 0.66830027, 0.66096669],
        ...,
        [0.55567437, 0.59997034, 0.58947015],
        [0.6175279 , 0.66462761, 0.6409297 ],
        [0.55254292, 0.59598154, 0.57982206]],

       [[0.60281843, 0.65740299, 0.64122152],
        [0.59334934, 0.63653541, 0.6095897 ],
        [0.58102983, 0.65248263, 0.63535082],
        ...,
        [0.61299884, 0.66970962, 0.66328555],
        [0.63109589, 0.66380072, 0.63919896],
        [0.62967676, 0.67986584, 0.66403139]],

       [[0.63334441, 0.6783306 , 0.65827852],
        [0.62239134, 0.65625477, 0.64197904],
        [0.400343  , 0.44861609, 0.42678294],
        ...,
        [0.58999079, 0.62602735, 0.59570462],
        [0.60244119, 0.66949201, 0.65915191],
        [0.58913219, 0.63048553, 0.60342306]],

       ...,

       [[0.11906332, 0.26807168, 0.0767018 ],
        [0.1206926 , 0.29025331, 0.13390706],
        [0.11865402, 0

array([[[0.60549939, 0.66457164, 0.64172816],
        [0.64604759, 0.712331  , 0.69036412],
        [0.59109557, 0.66830027, 0.66096669],
        ...,
        [0.55567437, 0.59997034, 0.58947015],
        [0.6175279 , 0.66462761, 0.6409297 ],
        [0.55254292, 0.59598154, 0.57982206]],

       [[0.60281843, 0.65740299, 0.64122152],
        [0.59334934, 0.63653541, 0.6095897 ],
        [0.58102983, 0.65248263, 0.63535082],
        ...,
        [0.61299884, 0.66970962, 0.66328555],
        [0.63109589, 0.66380072, 0.63919896],
        [0.62967676, 0.67986584, 0.66403139]],

       [[0.63334441, 0.6783306 , 0.65827852],
        [0.62239134, 0.65625477, 0.64197904],
        [0.400343  , 0.44861609, 0.42678294],
        ...,
        [0.58999079, 0.62602735, 0.59570462],
        [0.60244119, 0.66949201, 0.65915191],
        [0.58913219, 0.63048553, 0.60342306]],

       ...,

       [[0.11906332, 0.26807168, 0.0767018 ],
        [0.1206926 , 0.29025331, 0.13390706],
        [0.11865402, 0

keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.shape (1, 1, 1, 27, 5)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([45 45], shape=(2,), dtype=int32)
keep_channels 9 keep_max 80.0
keep_channels 9
ufilts.shape (1, 1, 1, 45, 9)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([81 81], shape=(2,), dtype=int32)
keep_channels 16 keep_max 576.0
keep_channels 16
ufilts.shape (1, 1, 1, 81, 16)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 16)
keep_percent 0.20629283704945683
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 5 keep_max 12.0
keep_channels 5
ufilts.

array([[[0.09422679, 0.04183781, 0.03937486],
        [0.08086177, 0.03921569, 0.03921569],
        [0.09707487, 0.0421729 , 0.03921569],
        ...,
        [0.11764706, 0.0627451 , 0.05098039],
        [0.10897671, 0.05658701, 0.03961134],
        [0.10993581, 0.05503384, 0.04326914]],

       [[0.16375564, 0.09302213, 0.08594229],
        [0.08457462, 0.04116857, 0.03921569],
        [0.07127997, 0.03921569, 0.03921569],
        ...,
        [0.11764706, 0.0627451 , 0.05098039],
        [0.10140142, 0.05732279, 0.04369662],
        [0.10370974, 0.05413866, 0.04844013]],

       [[0.12636121, 0.06520996, 0.05603626],
        [0.08510383, 0.04010202, 0.03921569],
        [0.09079447, 0.0432914 , 0.04052591],
        ...,
        [0.1259038 , 0.06708027, 0.05531557],
        [0.09399295, 0.04067096, 0.03921569],
        [0.09603104, 0.04112908, 0.03921569]],

       ...,

       [[0.14958641, 0.08291973, 0.05154718],
        [0.14837192, 0.0848652 , 0.05741422],
        [0.1445042 , 0

array([[[0.27665442, 0.21075846, 0.13194174],
        [0.21295957, 0.15444241, 0.09028799],
        [0.12193963, 0.07543562, 0.03921569],
        ...,
        [0.94320184, 0.92671233, 0.90162379],
        [0.938411  , 0.92664629, 0.89919531],
        [0.94685733, 0.93509263, 0.91548479]],

       [[0.275866  , 0.21134393, 0.12647873],
        [0.20884173, 0.15032457, 0.08757947],
        [0.11521619, 0.07073089, 0.03921569],
        ...,
        [0.9393689 , 0.91976106, 0.89623165],
        [0.94218755, 0.9276042 , 0.90156251],
        [0.94035745, 0.92859274, 0.9089849 ]],

       [[0.27720255, 0.20980728, 0.12193628],
        [0.20845637, 0.14993922, 0.08719411],
        [0.09975203, 0.06059475, 0.03921569],
        ...,
        [0.93333334, 0.92156863, 0.89411765],
        [0.93925685, 0.92825764, 0.9005515 ],
        [0.94310331, 0.93133861, 0.91173077]],

       ...,

       [[0.46844363, 0.44920343, 0.35294119],
        [0.47174239, 0.44539437, 0.35268605],
        [0.46666667, 0

array([[[0.27665442, 0.21075846, 0.13194174],
        [0.21295957, 0.15444241, 0.09028799],
        [0.12193963, 0.07543562, 0.03921569],
        ...,
        [0.94320184, 0.92671233, 0.90162379],
        [0.938411  , 0.92664629, 0.89919531],
        [0.94685733, 0.93509263, 0.91548479]],

       [[0.275866  , 0.21134393, 0.12647873],
        [0.20884173, 0.15032457, 0.08757947],
        [0.11521619, 0.07073089, 0.03921569],
        ...,
        [0.9393689 , 0.91976106, 0.89623165],
        [0.94218755, 0.9276042 , 0.90156251],
        [0.94035745, 0.92859274, 0.9089849 ]],

       [[0.27720255, 0.20980728, 0.12193628],
        [0.20845637, 0.14993922, 0.08719411],
        [0.09975203, 0.06059475, 0.03921569],
        ...,
        [0.93333334, 0.92156863, 0.89411765],
        [0.93925685, 0.92825764, 0.9005515 ],
        [0.94310331, 0.93133861, 0.91173077]],

       ...,

       [[0.46844363, 0.44920343, 0.35294119],
        [0.47174239, 0.44539437, 0.35268605],
        [0.46666667, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
ufilts.shape (1, 1, 1, 27, 8)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([72 72], shape=(2,), dtype=int32)
keep_channels 23 keep_max 128.0
keep_channels 23
ufilts.shape (1, 1, 1, 72, 23)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([207 207], shape=(2,), dtype=int32)
keep_channels 67 keep_max 1472.0
keep_channels 67
ufilts.shape (1, 1, 1, 207, 67)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 67)
keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
u

array([[[0.19852822, 0.36832109, 0.04953925],
        [0.30935514, 0.43004701, 0.16175658],
        [0.3805334 , 0.55946165, 0.31471452],
        ...,
        [0.35429856, 0.49036792, 0.2116022 ],
        [0.34852129, 0.45088491, 0.16751733],
        [0.19082054, 0.33976477, 0.08803017]],

       [[0.20182291, 0.37418455, 0.07316081],
        [0.27575397, 0.40259844, 0.14393431],
        [0.45678306, 0.63171965, 0.39507124],
        ...,
        [0.31848219, 0.42906207, 0.16560489],
        [0.35470283, 0.46151507, 0.19448698],
        [0.27123523, 0.35566792, 0.12825929]],

       [[0.23838179, 0.37771067, 0.03161765],
        [0.27300069, 0.41972777, 0.13309829],
        [0.35724428, 0.52887559, 0.28174764],
        ...,
        [0.36018687, 0.44800931, 0.16328269],
        [0.32452777, 0.43143383, 0.19690828],
        [0.35946691, 0.41019025, 0.21563169]],

       ...,

       [[0.29568136, 0.4114483 , 0.2784546 ],
        [0.28257078, 0.42929831, 0.22892374],
        [0.34065923, 0

array([[[0.0159869 , 0.03167318, 0.02775161],
        [0.00330882, 0.0189951 , 0.01507353],
        [0.04877451, 0.06764706, 0.06213235],
        ...,
        [0.09047373, 0.08581687, 0.0881453 ],
        [0.09405638, 0.08498774, 0.08890931],
        [0.10256778, 0.08688151, 0.09080308]],

       [[0.02085057, 0.03653684, 0.03261527],
        [0.00718827, 0.02297794, 0.01900467],
        [0.04873813, 0.06768344, 0.06213235],
        ...,
        [0.09403148, 0.08937462, 0.0918256 ],
        [0.09588504, 0.08680683, 0.09086052],
        [0.10580385, 0.0900563 , 0.09416169]],

       [[0.02546147, 0.04396638, 0.03863549],
        [0.00611596, 0.0288603 , 0.0214097 ],
        [0.04644608, 0.0699755 , 0.06213235],
        ...,
        [0.08768383, 0.08245443, 0.09601716],
        [0.08952206, 0.07984069, 0.09503677],
        [0.09944853, 0.07984069, 0.09834559]],

       ...,

       [[0.45220971, 0.43983227, 0.46657667],
        [0.45186314, 0.43850529, 0.46556371],
        [0.44268727, 0

array([[[0.0159869 , 0.03167318, 0.02775161],
        [0.00330882, 0.0189951 , 0.01507353],
        [0.04877451, 0.06764706, 0.06213235],
        ...,
        [0.09047373, 0.08581687, 0.0881453 ],
        [0.09405638, 0.08498774, 0.08890931],
        [0.10256778, 0.08688151, 0.09080308]],

       [[0.02085057, 0.03653684, 0.03261527],
        [0.00718827, 0.02297794, 0.01900467],
        [0.04873813, 0.06768344, 0.06213235],
        ...,
        [0.09403148, 0.08937462, 0.0918256 ],
        [0.09588504, 0.08680683, 0.09086052],
        [0.10580385, 0.0900563 , 0.09416169]],

       [[0.02546147, 0.04396638, 0.03863549],
        [0.00611596, 0.0288603 , 0.0214097 ],
        [0.04644608, 0.0699755 , 0.06213235],
        ...,
        [0.08768383, 0.08245443, 0.09601716],
        [0.08952206, 0.07984069, 0.09503677],
        [0.09944853, 0.07984069, 0.09834559]],

       ...,

       [[0.45220971, 0.43983227, 0.46657667],
        [0.45186314, 0.43850529, 0.46556371],
        [0.44268727, 0

keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
ufilts.shape (1, 1, 1, 27, 8)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([72 72], shape=(2,), dtype=int32)
keep_channels 23 keep_max 128.0
keep_channels 23
ufilts.shape (1, 1, 1, 72, 23)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([207 207], shape=(2,), dtype=int32)
keep_channels 67 keep_max 1472.0
keep_channels 67
ufilts.shape (1, 1, 1, 207, 67)
end loop 16.0
saving to: models/pets_seg
out.shape (1, 16, 16, 67)
keep_percent 0.3274694665458121
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 8 keep_max 12.0
keep_channels 8
u

array([[[0.31860641, 0.13815105, 0.10674402],
        [0.33202359, 0.14538144, 0.11572457],
        [0.33068323, 0.14020182, 0.10919884],
        ...,
        [0.49334598, 0.23664981, 0.17782438],
        [0.50927162, 0.26289639, 0.20607576],
        [0.497482  , 0.24910578, 0.1908586 ]],

       [[0.34208602, 0.14579505, 0.11880171],
        [0.35385647, 0.15967372, 0.13746361],
        [0.26899126, 0.10922948, 0.08377949],
        ...,
        [0.49941599, 0.25490004, 0.19330001],
        [0.50368607, 0.23194318, 0.17092142],
        [0.50926203, 0.27453855, 0.2005285 ]],

       [[0.34164369, 0.15403263, 0.11747664],
        [0.33651197, 0.14459254, 0.10982307],
        [0.34572801, 0.15018958, 0.11679879],
        ...,
        [0.50106275, 0.28470817, 0.23556413],
        [0.49273515, 0.25688764, 0.18729128],
        [0.51670116, 0.29966682, 0.24103861]],

       ...,

       [[0.06910425, 0.03921569, 0.03921569],
        [0.06378677, 0.03921569, 0.03921569],
        [0.02757353, 0

array([[[0.62199903, 0.64621943, 0.64365286],
        [0.72352368, 0.71626765, 0.71750367],
        [0.76392466, 0.78608376, 0.75687808],
        ...,
        [0.75577229, 0.70961583, 0.73460191],
        [0.6954298 , 0.6677134 , 0.69121218],
        [0.58642441, 0.62275511, 0.58029187]],

       [[0.62888139, 0.72010887, 0.66819352],
        [0.64491564, 0.71875054, 0.66369414],
        [0.66482937, 0.7341603 , 0.66749483],
        ...,
        [0.78940386, 0.80270159, 0.74222916],
        [0.72543108, 0.70899349, 0.72100449],
        [0.54852873, 0.5298146 , 0.56380141]],

       [[0.57833666, 0.7099126 , 0.6201787 ],
        [0.5508787 , 0.67490143, 0.56460971],
        [0.41901711, 0.52541125, 0.41333705],
        ...,
        [0.8447876 , 0.83995408, 0.78687507],
        [0.81122428, 0.79445899, 0.79746258],
        [0.75055432, 0.71288729, 0.76577413]],

       ...,

       [[0.31992164, 0.5900405 , 0.39025354],
        [0.41478297, 0.62211055, 0.44169971],
        [0.36633876, 0

array([[[0.62199903, 0.64621943, 0.64365286],
        [0.72352368, 0.71626765, 0.71750367],
        [0.76392466, 0.78608376, 0.75687808],
        ...,
        [0.75577229, 0.70961583, 0.73460191],
        [0.6954298 , 0.6677134 , 0.69121218],
        [0.58642441, 0.62275511, 0.58029187]],

       [[0.62888139, 0.72010887, 0.66819352],
        [0.64491564, 0.71875054, 0.66369414],
        [0.66482937, 0.7341603 , 0.66749483],
        ...,
        [0.78940386, 0.80270159, 0.74222916],
        [0.72543108, 0.70899349, 0.72100449],
        [0.54852873, 0.5298146 , 0.56380141]],

       [[0.57833666, 0.7099126 , 0.6201787 ],
        [0.5508787 , 0.67490143, 0.56460971],
        [0.41901711, 0.52541125, 0.41333705],
        ...,
        [0.8447876 , 0.83995408, 0.78687507],
        [0.81122428, 0.79445899, 0.79746258],
        [0.75055432, 0.71288729, 0.76577413]],

       ...,

       [[0.31992164, 0.5900405 , 0.39025354],
        [0.41478297, 0.62211055, 0.44169971],
        [0.36633876, 0

  0%|          | 0/7049 [00:00<?, ?it/s]

keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channels 10
ufilts.shape (1, 1, 1, 27, 10)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([90 90], shape=(2,), dtype=int32)
keep_channels 33 keep_max 160.0
keep_channels 33
ufilts.shape (1, 1, 1, 90, 33)
end loop 32.0
Starting level 2
Completing 16.0
pca shape tf.Tensor([297 297], shape=(2,), dtype=int32)
keep_channels 111 keep_max 2112.0
keep_channels 111
ufilts.shape (1, 1, 1, 297, 111)
end loop 16.0
saving to: models/pets_img
out.shape (1, 16, 16, 111)
keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channe

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])>]
Consider rewriting this model with the Functional API.


array([[[0.31272358, 0.32361558, 0.29820484],
        [0.31193513, 0.32502395, 0.29021668],
        [0.3099868 , 0.33001161, 0.29664665],
        ...,
        [0.28866425, 0.25707817, 0.21427792],
        [0.28846318, 0.24594535, 0.19817851],
        [0.2431497 , 0.240153  , 0.19564041]],

       [[0.32199422, 0.33907256, 0.29442403],
        [0.31503335, 0.32776743, 0.288838  ],
        [0.32305023, 0.34004864, 0.300248  ],
        ...,
        [0.26030803, 0.19661602, 0.14610907],
        [0.24157429, 0.20276742, 0.15124559],
        [0.23732623, 0.20338351, 0.18857566]],

       [[0.33531091, 0.34315404, 0.29845428],
        [0.33677572, 0.34288642, 0.30244812],
        [0.35008377, 0.35924432, 0.33313182],
        ...,
        [0.24312434, 0.1840155 , 0.13597628],
        [0.26333824, 0.1853219 , 0.14950694],
        [0.23001255, 0.20721652, 0.1820188 ]],

       ...,

       [[0.48685852, 0.49200368, 0.28987777],
        [0.49323493, 0.53634971, 0.29418996],
        [0.57753813, 0

array([[[0.31272358, 0.32361558, 0.29820484],
        [0.31193513, 0.32502395, 0.29021668],
        [0.3099868 , 0.33001161, 0.29664665],
        ...,
        [0.28866425, 0.25707817, 0.21427792],
        [0.28846318, 0.24594535, 0.19817851],
        [0.2431497 , 0.240153  , 0.19564041]],

       [[0.32199422, 0.33907256, 0.29442403],
        [0.31503335, 0.32776743, 0.288838  ],
        [0.32305023, 0.34004864, 0.300248  ],
        ...,
        [0.26030803, 0.19661602, 0.14610907],
        [0.24157429, 0.20276742, 0.15124559],
        [0.23732623, 0.20338351, 0.18857566]],

       [[0.33531091, 0.34315404, 0.29845428],
        [0.33677572, 0.34288642, 0.30244812],
        [0.35008377, 0.35924432, 0.33313182],
        ...,
        [0.24312434, 0.1840155 , 0.13597628],
        [0.26333824, 0.1853219 , 0.14950694],
        [0.23001255, 0.20721652, 0.1820188 ]],

       ...,

       [[0.48685852, 0.49200368, 0.28987777],
        [0.49323493, 0.53634971, 0.29418996],
        [0.57753813, 0

keep_percent 0.374858962356333
meanimg.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
self.mean.dtype <dtype: 'float64'>
Starting level 0
Completing 64.0
pca shape tf.Tensor([27 27], shape=(2,), dtype=int32)
keep_channels 10 keep_max 12.0
keep_channels 10
ufilts.shape (1, 1, 1, 27, 10)
end loop 64.0
Starting level 1
Completing 32.0
pca shape tf.Tensor([90 90], shape=(2,), dtype=int32)
keep_channels 33 keep_max 160.0
keep_channels 33
ufilts.shape (1, 1, 1, 90, 33)
end loop 32.0
Starting level 2


In [26]:
peformance_df = df[["training_data_size","count","keep_percent","resolution",'dice_mean_test', 'dice_mean_train',
       'dice_std_test', 'dice_std_train',"linear_inverse_train_time","img_train_time","seg_train_time","img_channel_size"]]

In [27]:
peformance_df.replace({np.nan:int(img_train.cardinality())})

training_data_size  count  keep_percent  resolution  dice_mean_test  \
0                7049    4.0           0.1       128.0        0.603597   
1                7049    4.0           0.2       128.0        0.603490   
2                7049    4.0           0.4       128.0        0.603496   
3                7049    4.0           0.6       128.0        0.603429   
4                7049    4.0           0.8       128.0        0.335789   

   dice_mean_train  dice_std_test  dice_std_train  linear_inverse_train_time  \
0         0.596743       0.181516        0.182701                  69.234996   
1         0.596670       0.181426        0.182620                  85.138880   
2         0.596668       0.181442        0.182621                 106.014822   
3         0.596622       0.181405        0.182585                 143.232454   
4         0.322221       0.244324        0.252329                 247.535285   

   img_train_time  seg_train_time  img_channel_size  
0      117.951081      117.951081              65.0  
1      142.841959      142.841959             149.0  
2      186.633168      186.633168             283.0  
3      276.932203      276.932203             433.0  
4      307.982901      307.982901             586.0

In [ ]:
peformance_df[["dice_mean_test","dice_mean_train"]].boxplot()

In [ ]:
peformance_df[["dice_std_test","dice_std_train"]].boxplot()

In [ ]:

reconstruct = seghead(next(iter(seg_train))[0]).shape
skip = np.random.randint(0,70)
image,seg_base = next(iter(zip(img_test.skip(skip),seg_test.skip(skip))))
imgdecom = imghead(image[0])
imgdecom = tf.reshape(imgdecom,(1,-1))
segdecom = tf.linalg.matvec(A,imgdecom,transpose_a=True)+b
seg = seginvhead(tf.reshape(segdecom,(reconstruct)))
y_true = tf.cast(tf.reduce_min(seg_base[0],2)==0,tf.float64)
y_pred = tf.cast(tf.reduce_min(seg[0],2)<threshold_intensity,tf.float64)
plt.subplot(2,1,1)
plt.imshow(np.hstack([image[0],seg_base[0],seg[0]]))
plt.subplot(2,1,2)
plt.imshow(np.hstack([y_true,y_pred]))


In [ ]:

skip = np.random.randint(0,70)
image,seg_base = next(iter(zip(img_test.skip(skip),seg_test.skip(skip))))
imgdecom = imghead(image[0])
conv = tf.nn.conv2d(imgdecom, A,1,"VALID")
conv = tf.nn.bias_add(conv,b)
seg = seginvhead(conv)
y_true = tf.cast(tf.reduce_min(seg_base[0],2)==0,tf.float64)
y_pred = tf.cast(tf.reduce_min(seg[0],2)<threshold_intensity,tf.float64)
plt.subplot(2,1,1)
plt.imshow(np.hstack([image[0],seg_base[0],seg[0]]))
plt.subplot(2,1,2)
plt.imshow(np.hstack([y_true,y_pred]))